class MarketStockList {
  static final List<Map<String, String>> companies = [
    {"id": "1", "name": "Reliance Industries", "symbol": "RELIANCE", "exchange": "NSE"},
    {"id": "2", "name": "Tata Motors", "symbol": "TATAMOTORS", "exchange": "NSE"},
    {"id": "3", "name": "Infosys", "symbol": "INFY", "exchange": "BSE"},
    {"id": "4", "name": "HDFC Bank", "symbol": "HDFCBANK", "exchange": "NSE"},
    {"id": "5", "name": "ICICI Bank", "symbol": "ICICIBANK", "exchange": "BSE"},
    {"id": "6", "name": "Larsen & Toubro", "symbol": "LT", "exchange": "NSE"},
    {"id": "7", "name": "State Bank of India", "symbol": "SBIN", "exchange": "BSE"},
    {"id": "8", "name": "Bharti Airtel", "symbol": "BHARTIARTL", "exchange": "NSE"},
    {"id": "9", "name": "Maruti Suzuki", "symbol": "MARUTI", "exchange": "BSE"},
    {"id": "10", "name": "Wipro", "symbol": "WIPRO", "exchange": "NSE"},
    {"id": "11", "name": "Hindustan Unilever", "symbol": "HINDUNILVR", "exchange": "BSE"},
    {"id": "12", "name": "TCS", "symbol": "TCS", "exchange": "NSE"},
    {"id": "13", "name": "Adani Enterprises", "symbol": "ADANIENT", "exchange": "NSE"},
    {"id": "14", "name": "Bajaj Finance", "symbol": "BAJFINANCE", "exchange": "BSE"},
    {"id": "15", "name": "Asian Paints", "symbol": "ASIANPAINT", "exchange": "NSE"},
    {"id": "16", "name": "Axis Bank", "symbol": "AXISBANK", "exchange": "NSE"},
    {"id": "17", "name": "Tata Steel", "symbol": "TATASTEEL", "exchange": "BSE"},
    {"id": "18", "name": "Sun Pharma", "symbol": "SUNPHARMA", "exchange": "NSE"},
    {"id": "19", "name": "Coal India", "symbol": "COALINDIA", "exchange": "BSE"},
    {"id": "20", "name": "Nestle India", "symbol": "NESTLEIND", "exchange": "NSE"},
    {"id": "21", "name": "Power Grid Corporation", "symbol": "POWERGRID", "exchange": "NSE"},
    {"id": "22", "name": "Dr Reddy's Labs", "symbol": "DRREDDY", "exchange": "BSE"},
    {"id": "23", "name": "Ultratech Cement", "symbol": "ULTRACEMCO", "exchange": "NSE"},
    {"id": "24", "name": "Grasim Industries", "symbol": "GRASIM", "exchange": "BSE"},
    {"id": "25", "name": "HCL Technologies", "symbol": "HCLTECH", "exchange": "NSE"},
    {"id": "26", "name": "Mahindra & Mahindra", "symbol": "M&M", "exchange": "NSE"},
    {"id": "27", "name": "Bajaj Auto", "symbol": "BAJAJ-AUTO", "exchange": "BSE"},
    {"id": "28", "name": "Eicher Motors", "symbol": "EICHERMOT", "exchange": "NSE"},
    {"id": "29", "name": "Titan Company", "symbol": "TITAN", "exchange": "BSE"},
    {"id": "30", "name": "NTPC", "symbol": "NTPC", "exchange": "NSE"},
    {"id": "31", "name": "IndusInd Bank", "symbol": "INDUSINDBK", "exchange": "NSE"},
    {"id": "32", "name": "Tech Mahindra", "symbol": "TECHM", "exchange": "BSE"},
    {"id": "33", "name": "JSW Steel", "symbol": "JSWSTEEL", "exchange": "NSE"},
    {"id": "34", "name": "Pidilite Industries", "symbol": "PIDILITIND", "exchange": "NSE"},
    {"id": "35", "name": "Bharat Petroleum", "symbol": "BPCL", "exchange": "BSE"},
    {"id": "36", "name": "Havells India", "symbol": "HAVELLS", "exchange": "NSE"},
    {"id": "37", "name": "Godrej Consumer", "symbol": "GODREJCP", "exchange": "BSE"},
    {"id": "38", "name": "Dabur India", "symbol": "DABUR", "exchange": "NSE"},
    {"id": "39", "name": "Britannia Industries", "symbol": "BRITANNIA", "exchange": "BSE"},
    {"id": "40", "name": "Zomato", "symbol": "ZOMATO", "exchange": "NSE"},
    {"id": "41", "name": "Hindalco", "symbol": "HINDALCO", "exchange": "BSE"},
    {"id": "42", "name": "Apollo Hospitals", "symbol": "APOLLOHOSP", "exchange": "NSE"},
    {"id": "43", "name": "Lupin", "symbol": "LUPIN", "exchange": "BSE"},
    {"id": "44", "name": "Siemens", "symbol": "SIEMENS", "exchange": "NSE"},
    {"id": "45", "name": "BHEL", "symbol": "BHEL", "exchange": "BSE"},
    {"id": "46", "name": "Motherson Sumi", "symbol": "MOTHERSUMI", "exchange": "NSE"},
    {"id": "47", "name": "ABB India", "symbol": "ABB", "exchange": "BSE"},
    {"id": "48", "name": "IRCTC", "symbol": "IRCTC", "exchange": "NSE"},
    {"id": "49", "name": "HDFC Life", "symbol": "HDFCLIFE", "exchange": "BSE"},
    {"id": "50", "name": "SBI Life Insurance", "symbol": "SBILIFE", "exchange": "NSE"},
    {"id": "51", "name": "Ambuja Cements", "symbol": "AMBUJACEM", "exchange": "BSE"},
    {"id": "52", "name": "Indian Oil Corporation", "symbol": "IOC", "exchange": "NSE"},
    {"id": "53", "name": "Adani Green Energy", "symbol": "ADANIGREEN", "exchange": "BSE"},
    {"id": "54", "name": "Vedanta", "symbol": "VEDL", "exchange": "NSE"},
    {"id": "55", "name": "Tata Power", "symbol": "TATAPOWER", "exchange": "BSE"},
  ];
}
